version: '3.9'

services:
  app:
    container_name: rossum-exporter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      ROSSUM_USERNAME: 'myUser123'
      ROSSUM_PASSWORD: 'secretSecret'
      DEBUG: 'false'